// Auto-generated by wrangler types
interface CloudflareEnv {
	ASSETS: Fetcher;
	DATABASE_URL: string;
}

declare global {
	namespace App {
		interface Platform {
			env: CloudflareEnv;
		}
	}
}

export {};
